name: Rust Compiler Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ go, js ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set up Go
        if: matrix.target == 'go' || matrix.target == 'default'
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
          check-latest: false

      - name: Set up Node.js
        if: matrix.target == 'js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            compiler/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run default tests
        if: matrix.target == 'go'
        working-directory: ./compiler
        run: cargo run -- test ../tests

      - name: Run tests with target
        working-directory: ./compiler
        run: cargo run -- test ../tests --target ${{ matrix.target }}

      - name: Make regression test script executable
        run: chmod +x ./regression_tests/test_runner.sh

      - name: Run regression tests
        working-directory: ./regression_tests
        run: ./test_runner.sh